### ISSUE TITLE
Find potentials employees for UNITBV student restaurant.

### ISSUE THREAD

**Issue by iosifnicolae2** [iosifnicolae2/unitbv_backend#7]
## Why 
Unitbv restaurant needs more employees to serve students that eat at the restaurant(more than 500).
## What
- [ ] A template is created to be used to give information about open job positions at the restaurant. #1
  - [ ] The above page contains a section with job description, some photos and a button that will redirect the user to a Google Forms #1
- [ ] Search for job description that we want to promote(in this issue we will search for information and complete the above page with those ones) #2
- [ ] Implement inline social share buttons(Facebook, Twitter and Google) - https://www.addthis.com/get/share #3
- [ ] Add content to the Facebook page(profile photo, cover photo, descriptions, schedule, etc.) #4
- [ ] Implement Google Analytics #5
- [ ] Think how to promote the `Job description` page #6

---
